# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_auto_20151105_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Type'),
        ),
    ]
